// BotState — todos os estados possíveis da máquina de estado
enum BotState {
  START                     = 'start',
  ORDERING                  = 'ordering',
  ORDERING_CAT              = 'ordering_cat',
  BROWSING_CATEGORIES       = 'browsing_categories',
  ORDERING_ITEMS            = 'ordering_items',
  BROWSING_ITEMS            = 'browsing_items',
  AWAITING_QTY              = 'awaiting_qty',
  AWAITING_MORE             = 'awaiting_more',
  CONFIRMING                = 'confirming',
  AWAITING_TYPE             = 'awaiting_type',
  AWAITING_ADDRESS          = 'awaiting_address',
  AWAITING_ADDRESS_NUMBER   = 'awaiting_address_number',
  AWAITING_COMPLEMENT       = 'awaiting_complement',
  OFFER_PICKUP              = 'offer_pickup',
  AWAITING_PAYMENT          = 'awaiting_payment',
  AWAITING_CHANGE           = 'awaiting_change',
  AWAITING_SPLIT_COUNT      = 'awaiting_split_count',
  AWAITING_SPLIT_PAYMENT    = 'awaiting_split_payment',
  AWAITING_SPLIT_CHANGE     = 'awaiting_split_change',
  AWAITING_MIXED_METHOD     = 'awaiting_mixed_method',
  AWAITING_MIXED_AMOUNT     = 'awaiting_mixed_amount',
  AWAITING_MIXED_CHANGE     = 'awaiting_mixed_change',
  REPEAT_ORDER              = 'repeat_order',
  AWAITING_NAME             = 'awaiting_name',
  HUMAN_HANDOFF             = 'human_handoff',
  AWAITING_ORDER_DETAIL     = 'awaiting_order_detail',
  NOTIFICATIONS_MENU        = 'notifications_menu',
  AWAITING_MARKETING_OPT_IN = 'awaiting_marketing_opt_in',
  RESERVING                 = 'reserving',
  CONFIRMING_RESERVATION    = 'confirming_reservation',
}

// Estados onde o usuário digita INPUT livre (não atalhos de menu)
const ExpectingRawInputStates: ReadonlyArray<string> = [
  BotState.ORDERING_CAT,
  BotState.BROWSING_CATEGORIES,
  BotState.ORDERING_ITEMS,
  BotState.BROWSING_ITEMS,
  BotState.AWAITING_QTY,
  BotState.AWAITING_MORE,
  BotState.ORDERING,
  BotState.AWAITING_ADDRESS,
  BotState.AWAITING_ADDRESS_NUMBER,
  BotState.AWAITING_COMPLEMENT,
  BotState.AWAITING_CHANGE,
  BotState.AWAITING_SPLIT_COUNT,
  BotState.AWAITING_SPLIT_CHANGE,
  BotState.AWAITING_MIXED_AMOUNT,
  BotState.AWAITING_MIXED_CHANGE,
  BotState.AWAITING_NAME,
  BotState.RESERVING,
];
